services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/library_db
      - REDIS_URL=redis://redis:6379/0
      - SMTP_HOST=smtp.example.com
      - SMTP_PORT=587
      - SMTP_USER=user@example.com
      - SMTP_PASSWORD=yourpassword
      - JWT_SECRET_KEY=your_jwt_secret_key_here
    depends_on:
      - postgres
      - redis
  celery:
    build: .
    command: celery -A app.tasks.email_tasks:app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/library_db
      - REDIS_URL=redis://redis:6379/0
      - SMTP_HOST=smtp.example.com
      - SMTP_PORT=587
      - SMTP_USER=user@example.com
      - SMTP_PASSWORD=yourpassword
      - JWT_SECRET_KEY=your_jwt_secret_key_here
    depends_on:
      - redis
      - postgres
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=library_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2
volumes:
  postgres_data: